### ISSUE TITLE
No module named 'depend'报错

### ISSUE THREAD

**Issue by AsoulDianava** [keven1024/qinglong_helper#1]
No module named 'depend'
在尝试了[这个方案](https://thin-hill-428.notion.site/QL-pannel-Dependent-Librai-164400378c7f4a4587f976e89aea1584) 后还是一样

**Comment by keven1024** [comment]
确保你运行的 [ql_log_scan.py](https://github.com/keven1024/qinglong_helper/blob/master/ql_log_scan.py) 和 [depend.py](https://github.com/keven1024/qinglong_helper/blob/master/depend.py) 放在同一个目录。

`ql_log_scan.py` 运行时会调用同目录下的 `depend.py`

**Comment by AsoulDianava** [comment]
> 确保你运行的 [ql_log_scan.py](https://github.com/keven1024/qinglong_helper/blob/master/ql_log_scan.py) 和 [depend.py](https://github.com/keven1024/qinglong_helper/blob/master/depend.py) 放在同一个目录。
> 
> `ql_log_scan.py` 运行时会调用同目录下的 `depend.py`

![IMG_20220606_135705](https://user-images.githubusercontent.com/93473203/172103783-2dcc6a96-cad5-47da-a299-653f31221a43.jpg)
有的

**Comment by keven1024** [comment]
> > 确保你运行的 [ql_log_scan.py](https://github.com/keven1024/qinglong_helper/blob/master/ql_log_scan.py) 和 [depend.py](https://github.com/keven1024/qinglong_helper/blob/master/depend.py) 放在同一个目录。
> > `ql_log_scan.py` 运行时会调用同目录下的 `depend.py`
> 
> ![IMG_20220606_135705](https://user-images.githubusercontent.com/93473203/172103783-2dcc6a96-cad5-47da-a299-653f31221a43.jpg) 有的

是script下的要放在同一个目录，你可以在网页端检查depend.py是否存在同一目录下
![image](https://user-images.githubusercontent.com/99848979/172401980-306a26b2-d08a-4f81-9b76-597f18b444e7.png)
