### ISSUE TITLE
报错 ，提示我有其他脚本分析存在

### ISSUE THREAD

**Issue by miss537** [keven1024/qinglong_helper#4]
☺当前脚本目录为: /ql/scripts/keven1024_qinglong_helper/ql_log_scan.py
🙄检测到其他同类型的青龙日志分析脚本存在，拒绝运行!

我就是先自己从你这下了压缩包，完事自己手动添加的任务。后来感觉更新不方便，就拉的库，那么弄的 ，结果就提示我这个了

**Comment by keven1024** [comment]
> ☺当前脚本目录为: /ql/scripts/keven1024_qinglong_helper/ql_log_scan.py 🙄检测到其他同类型的青龙日志分析脚本存在，拒绝运行!
> 
> 我就是先自己从你这下了压缩包，完事自己手动添加的任务。后来感觉更新不方便，就拉的库，那么弄的 ，结果就提示我这个了

默认脚本会在青龙目录下创建一个文件用于唯一标识，防止多个库使用同一个脚本打架，比如我用的别的库里禁用重复任务会出现互相禁用的情况
![image](https://user-images.githubusercontent.com/99848979/172436042-7f846b20-e1e5-4c49-95b8-f48aaea4001f.png)
现在加了一个新环境变量，更新一下脚本然后用这个 `QL_LOG_SCAN_SCRIPT_PATH` 环境变量，值为你想运行的脚本的地址
![image](https://user-images.githubusercontent.com/99848979/172437175-2f5a5e7a-6d8c-47b6-9c8c-12d82a79399a.png)
例：比如上面的图日志显示当前脚本目录为 `/ql/data/scripts/icu_qinglong_helper/ql_log_scan.py` ，变量就填
```
export QL_LOG_SCAN_SCRIPT_PATH="/ql/data/scripts/icu_qinglong_helper/ql_log_scan.py"
```
